apiVersion: v1
kind: Service              # 1
metadata:
  name: mattermost-prod
spec:
  type: NodePort       # 2
  ports:
  - port: 8065               # 3
    protocol: TCP          # 4
    targetPort: 8065         # 5
  selector:                # 6
    app: mattermost-prod       # 7

