apiVersion: v1
kind: Service              # 1
metadata:
  name: python-hello-web-foo
spec:
  type: NodePort       # 2
  ports:
  - port: 5000               # 3
    protocol: TCP          # 4
    targetPort: 5000         # 5
  selector:                # 6
    app: python-hello-web-foo       # 7

