apiVersion: extensions/v1beta1
kind: Deployment                                          # 1
metadata:
  name: python-hello-web-foo
  version: v1
spec:
  replicas: 1                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate: 
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:
    metadata:
      labels:
        app: python-hello-web-foo                                  # 6
        version: v1
    spec:
      containers:
        - image: haalcala/mattermost-prod
          imagePullPolicy: Always                         # 7
          name: python-hello-web-foo
          ports:
            - containerPort: 8065
          env:
            - name: __DB_HOST__
              value: mattermost-prod-test.cabldmnc4rgm.us-east-2.rds.amazonaws.com


