apiVersion: extensions/v1beta1
kind: Deployment                                          # 1
metadata:
  name: python-hello-web-internal
spec:
  replicas: 2                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate: 
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:
    metadata:
      labels:
        app: python-hello-web-internal                                  # 6
    spec:
      containers:
        - image: haalcala/python-hello-web-internal-v2
          imagePullPolicy: Always                         # 7
          name: python-hello-web-internal
          ports:
            - containerPort: 5000

